version: "3.1"
services:
  dl-manager:
    container_name: dl-manager
    build:
      context: ./
      dockerfile: Dockerfile-gpu
    image: dl-manager
    ports:
      - '9011:9011'

    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities:
                - "gpu"

