version: "3.1"
services:
  dl-manager:
    container_name: dl-manager
    build:
      context: ./
      dockerfile: Dockerfile-gpu
    image: dl-manager
    ports:
      - "9011:9011"
    networks:
      - maestro_traefik
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.dl-manager.rule=Host(`maestro.localhost`)"
      - "traefik.http.routers.dl-manager.rule=PathPrefix(`/dl-manager`)"
      - "traefik.http.routers.dl-manager.entrypoints=websecure"
      - "traefik.http.routers.dl-manager.tls=true"
      - "traefik.http.routers.dl-manager.middlewares=dl-manager"
      - "traefik.http.middlewares.dl-manager.stripprefix.prefixes=/dl-manager"

    deploy:
      resources:
        reservations:
          devices:
            - driver: "nvidia"
              capabilities:
                - "gpu"

networks:
  maestro_traefik:
    external: true
